# Generated by Django 3.1.3 on 2021-02-06 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0002_auto_20201213_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='instrument_type'),
        ),
        migrations.AlterField(
            model_name='userinstrument',
            name='experience_level',
            field=models.CharField(default=None, max_length=30, verbose_name='instrument_exp'),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='userImages/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
