# Generated by Django 3.1.3 on 2021-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20210206_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='userinstrument',
            name='experience_level',
            field=models.IntegerField(default=None, max_length=2, verbose_name='instrument_exp'),
        ),
    ]
