# Generated by Django 3.1.3 on 2021-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20210207_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstrument',
            name='experience_level',
            field=models.IntegerField(default=None, verbose_name='instrument_exp'),
        ),
    ]
