# Generated by Django 3.1.3 on 2021-02-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20210207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='town',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
