# Generated by Django 3.1.3 on 2021-02-16 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20210211_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance_limit',
            field=models.IntegerField(default=50, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='music_url',
            field=models.URLField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
