# Generated by Django 3.1.3 on 2021-02-16 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_auto_20210216_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='distance_limit',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
